export const data = [
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
  {
    rank: 1,
    img: "",
    name: "IIT Madras - Indian Institute of Technology - [IITM], Chennai",
    loaction: "Chennai, Tamil Nadu",
    approvals: "AICTE",
    fees: 209550,
    avgPackage: 2148000,
    highPackage: 1980000,
    rating: 8.6,
    reviews: 289,
    bestIn: "Social Life",
    ranking: "3rd/131",
    rankingBy: "",
  },
];
